Remove old build workflow.
Rename `build_v2.yaml` to `build.yaml` and remove "v2" suffixes. The
build configs and build scripts used by the old build workflow can also
be removed.

The new workflow decreased wall time from 20 minutes to 7 minutes, and
CPU time from 70 minutes to 7 minutes.

Change-Id: I9b67f52583126c6c17c723d70ffe1819bf46f5f9

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,9 +1,7 @@
-name: Build and attest all
+name: Build and attest
 
 on:
   push:
-    branches: [main]
-  pull_request:
     branches: [main]
 
 # See https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
@@ -12,121 +10,85 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  build_attest_all:
-    strategy:
-      fail-fast: false
-      matrix:
-        buildconfig:
-          - buildconfigs/agg_core.sh
-          - buildconfigs/fed_sql.sh
-          - buildconfigs/ledger_enclave_app.sh
-          - buildconfigs/sql_server.sh
+  build:
+    outputs:
+      binaries: ${{ steps.list-binaries.outputs.binaries }}
 
     permissions:
-      actions: read
-      id-token: write
-      attestations: write
       contents: read
 
     runs-on: ubuntu-20.04
 
     steps:
-      # Needed for GCS upload.
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Bazel
+        uses: bazel-contrib/setup-bazel@0.8.5
+        with:
+          bazelisk-cache: true
+          disk-cache: ${{ github.workflow }}
+          repository-cache: true
+      - name: Build
+        run: |
+          bazelisk run -c opt --curses=no --noshow_progress //:install_release_binaries -- --destdir="${{ runner.temp }}/binaries"
+      - name: List binaries
+        id: list-binaries
+        # Set the "binaries" output to a json-encoded list of the bazel build
+        # outputs, relative to `--destdir`. (e.g.
+        # ["agg_core/container.tar","ledger/binary"])
+        run: |
+          set -euxo pipefail
+          binaries="$(find "${{ runner.temp }}/binaries" -type f -printf '%P\n' | jq -Rsc 'split("\n")[:-1]')"
+          echo "binaries=${binaries}" >> "$GITHUB_OUTPUT"
+      - name: Upload binaries
+        uses: actions/upload-artifact@v4
+        with:
+          name: binaries
+          path: ${{ runner.temp }}/binaries/
+          if-no-files-found: error
+          retention-days: 5
+
+  attest:
+    needs: build
+
+    permissions:
+      id-token: write
+      attestations: write
+
+    runs-on: ubuntu-20.04
+
+    strategy:
+      # Continue attesting other artifacts even if one fails.
+      fail-fast: false
+      matrix:
+        binary: ${{ fromJson(needs.build.outputs.binaries) }}
+
+    steps:
+      - name: Download binaries
+        uses: actions/download-artifact@v4
+        with:
+          name: binaries
+      - name: Attest
+        id: attest
+        uses: actions/attest-build-provenance@v1
+        with:
+          subject-path: ${{ matrix.binary }}
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v2
         with:
           credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}
-
-      # Needed for GCS upload.
-      - name: Setup Google Cloud
+      - name: Setup gcloud
         uses: google-github-actions/setup-gcloud@v2
-
-      - name: Mount main branch
-        uses: actions/checkout@v4
-
-      # Keeps two versions of SUBJECT_PATHS, with space resp. comma as
-      # path separator. Both are needed in later steps.
-      - name: Parse buildconfig
-        id: parse
-        run: |
-          set -o errexit
-          set -o nounset
-          set -o pipefail
-          source ${{ matrix.buildconfig }}
-          echo "package-name=${PACKAGE_NAME}" >> "${GITHUB_OUTPUT}"
-          paths="${SUBJECT_PATHS[@]}"
-          echo "subject-paths=${paths}" >> "${GITHUB_OUTPUT}"
-          echo "subject-paths-commas=${paths// /,}" >> "${GITHUB_OUTPUT}"
-
-      - name: Show values
-        run: |
-          set -o errexit
-          set -o nounset
-          set -o pipefail
-          gsutil --version
-          echo "package_name: ${{ steps.parse.outputs.package-name }}"
-          echo "subject_paths: ${{ steps.parse.outputs.subject-paths }}"
-          echo "subject_paths_commas: ${{ steps.parse.outputs.subject-paths-commas }}"
-          echo "GITHUB_SHA: ${GITHUB_SHA}"
-
-      - name: Build
-        id: build
-        run: |
-          set -o errexit
-          set -o nounset
-          set -o pipefail
-          source ${{ matrix.buildconfig }}
-          eval "${BUILD_COMMAND[@]}"
-
-      - name: Show build artifacts
-        run: |
-          echo "${{ steps.parse.outputs.subject-paths }}"
-          ls -la ${{ steps.parse.outputs.subject-paths }}
-
-      - name: Attest
-        id: attest
-        uses: actions/attest-build-provenance@v1.1.1
         with:
-          subject-path: ${{ steps.parse.outputs.subject-paths-commas }}
-
-      - name: Show bundle
+          skip_install: true
+      - name: Upload provenance
         run: |
-          echo "${{ steps.attest.outputs.bundle-path }}"
-          ls -la "${{ steps.attest.outputs.bundle-path }}"
-          cat "${{ steps.attest.outputs.bundle-path }}"
+          set -euxo pipefail
 
-      # Upload binary and provenance to GCS and index via http://static.space
-      # so that, regardless of the GCS bucket and path, it can easily be
-      # located by its digest.
-      - name: Upload
-        id: upload
-        run: |
-          set -o errexit
-          set -o nounset
-          set -o pipefail
-          set -o xtrace
-
-          bucket=oak-bins
-          package_name=${{ steps.parse.outputs.package-name }}
-          subject_paths=( ${{ steps.parse.outputs.subject-paths }} )
-          binary_path="${subject_paths[0]}"
-          provenance_path=${{ steps.attest.outputs.bundle-path }}
-
-          gcs_binary_path="binary/${GITHUB_SHA}/${package_name}/binary"
+          binary_path="${{ matrix.binary }}"
+          package_name="${binary_path%%/*}"
+          provenance_path="${{ steps.attest.outputs.bundle-path }}"
           gcs_provenance_path="provenance/${GITHUB_SHA}/${package_name}/attestation.jsonl"
-          binary_url="https://storage.googleapis.com/${bucket}/${gcs_binary_path}"
-          provenance_url="https://storage.googleapis.com/${bucket}/${gcs_provenance_path}"
 
-          gsutil cp "${binary_path}" "gs://${bucket}/${gcs_binary_path}"
-          gsutil cp "${provenance_path}" "gs://${bucket}/${gcs_provenance_path}"
+          gsutil cp "${provenance_path}" "gs://oak-bins/${gcs_provenance_path}"
 
-          curl --fail \
-            --request POST \
-            --header 'Content-Type: application/json' \
-            --data "{ \"url\": \"${binary_url}\" }" \
-            https://api.static.space/v1/snapshot
-          curl --fail \
-            --request POST \
-            --header 'Content-Type: application/json' \
-            --data "{ \"url\": \"${provenance_url}\" }" \
-            https://api.static.space/v1/snapshot
